{% set name = "cuttools" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://www.ugr.es/~pittau/CutTools/cuttools_v{{ version }}.tar.gz
    sha256: 288374088b4050bf9546babdc02ddfd8d53dce8e5b86e0762241acb425551f23
    folder: source
    patches:
      # Don't built CutTools dependencies as these are installed through conda-forge
      - build-only-cuttools-in-makefile.patch

build:
  number: 0

outputs:
  - name: {{ name }}-static

    build:
      skip: true  # [win]
      script:
        # Enable extended-source with '-ffixed-line-length-none' for long lines
        # c.f. https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html#index-ffixed-line-length-n

        # Build
        - cd source
        - make PRECISION=QP FC=$FC FFLAGS="$FFLAGS -std=legacy -fno-automatic -O2 -funroll-all-loops -ffixed-line-length-none -I$PREFIX/include/mpfun90 -I$PREFIX/include/oneloop"

        # Install
        # Avoid vendoring FF headers and .dat
        - rm includects/ffs.h
        - rm includects/ff.h
        - rm includects/aa.h

        - mv includects/libcts.a $PREFIX/lib/
        - mkdir -p $PREFIX/include/cts
        - mv includects/*.h $PREFIX/include/cts/
        - mv includects/*.mod $PREFIX/include/cts/

        - make clean

    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('fortran') }}
        - make
        - libtool
      host:
        - mpfun90
        - oneloop

    test:
      source_files:
        - source/examples/numerators.f
        - source/examples/mpnumerators.f90
        - source/examples/rambo.f
        - source/examples/random.f
        - source/examples/testmp.f
        - source/examples/example0.f
        - source/examples/example1.f
      requires:
        - {{ compiler('fortran') }}
        - mpfun90
        - oneloop
        - qcdloop-fortran-static
      commands:
        - test -f $PREFIX/lib/libcts.a

        # FIXME: Verify this isn't vendoring FF headers and .dat
        - test -f $PREFIX/include/cts/cts_mpr.h
        - test -f $PREFIX/include/cts/cts_mpc.h
        - test -f $PREFIX/include/cts/cts_dpr.h
        - test -f $PREFIX/include/cts/cts_dpc.h
        - test -f $PREFIX/include/cts/cts_mpinit.h
        - test -f $PREFIX/include/cts/cts_mprec.h
        - test -f $PREFIX/include/cts/def_propagator.mod
        - test -f $PREFIX/include/cts/def_solcut.mod
        - test -f $PREFIX/include/cts/def_mp_propagator.mod
        - test -f $PREFIX/include/cts/def_mp_solcut.mod
        - test -f $PREFIX/include/cts/tensor_operations.mod
        - test -f $PREFIX/include/cts/constants.mod
        - test -f $PREFIX/include/cts/mbnvalues.mod
        - test -f $PREFIX/include/cts/maxnumden.mod
        - test -f $PREFIX/include/cts/maxsolutions.mod
        - test -f $PREFIX/include/cts/combinatorics.mod
        - test -f $PREFIX/include/cts/dimensions.mod
        - test -f $PREFIX/include/cts/inout.mod
        - test -f $PREFIX/include/cts/scale.mod
        - test -f $PREFIX/include/cts/qt2value.mod
        - test -f $PREFIX/include/cts/denominators.mod
        - test -f $PREFIX/include/cts/cuttings.mod
        - test -f $PREFIX/include/cts/coefficients.mod
        - test -f $PREFIX/include/cts/loopfunctions.mod
        - test -f $PREFIX/include/cts/mp_loopfunctions.mod
        - test -f $PREFIX/include/cts/countdigits.mod

        - cd source/examples/
        - $FC numerators.f mpnumerators.f90 rambo.f random.f testmp.f -o testmp $FFLAGS -std=legacy -I$CONDA_PREFIX/include/cts -I$CONDA_PREFIX/include/mpfun90 $LDFLAGS -lcts -lavh_olo -lmpfun90 -lqcdloop -lff
        - ./testmp

        - $FC numerators.f mpnumerators.f90 example0.f -o example0 $FFLAGS -std=legacy -I$CONDA_PREFIX/include/cts -I$CONDA_PREFIX/include/mpfun90 $LDFLAGS -lcts -lavh_olo -lmpfun90 -lqcdloop -lff
        - ./example0

        # Execution requires user input
        - $FC numerators.f mpnumerators.f90 rambo.f random.f example1.f -o example1 $FFLAGS -std=legacy -I$CONDA_PREFIX/include/cts -I$CONDA_PREFIX/include/mpfun90 $LDFLAGS -lcts -lavh_olo -lmpfun90 -lqcdloop -lff
        - test -f ./example1

about:
  home: https://www.ugr.es/~pittau/CutTools/
  summary: 'CutTools: Computing 1-loop amplitudes at the integrand level'
  description: |
    CutTools is based on the following papers:
      * G. Ossola, C. G. Papadopoulos and R. Pittau [JHEP 0803:042,2008](https://doi.org/10.1088/1126-6708/2008/03/042)
      * G. Ossola, C. G. Papadopoulos and R. Pittau [Nucl. Phys. B 763 (2007) 147](https://doi.org/10.1016/j.nuclphysb.2006.11.012)
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://www.ugr.es/~pittau/CutTools/
  doc_url: https://www.ugr.es/~pittau/CutTools/

extra:
  feedstock-name: cuttools
  recipe-maintainers:
    - matthewfeickert
